obj-$(CONFIG_TOUCHSCREEN_GOODIX_BRL) += goodix_core.o
goodix_core-y := goodix_ts_core.o goodix_brl_hw.o goodix_cfg_bin.o goodix_ts_utils.o
goodix_core-$(CONFIG_TOUCHSCREEN_GOODIX_BRL_I2C) += goodix_brl_i2c.o
goodix_core-$(CONFIG_TOUCHSCREEN_GOODIX_BRL_SPI) += goodix_brl_spi.o
goodix_core-$(CONFIG_TOUCHSCREEN_GOODIX_BRL_GESTURE) += goodix_ts_gesture.o
goodix_core-$(CONFIG_TOUCHSCREEN_GOODIX_BRL_INSPECT) += goodix_ts_inspect.o
goodix_core-$(CONFIG_TOUCHSCREEN_GOODIX_BRL_TOOLS) += goodix_ts_tools.o
goodix_core-$(CONFIG_TOUCHSCREEN_GOODIX_BRL_FW_UPDATE) += goodix_brl_fwupdate.o